management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: CLICommands1
    description: Spring Boot REST API for storing CLI commands.
    author: author
    version: '@project.version@'
spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher