spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: cli-db
  jpa:
    hibernate:
      ddl-auto: create-drop
#
#spring_profiles_active=prod
#PROD_DB_HOST=containers-us-west-111.railway.app
#PROD_DB_PORT=6531
#PROD_DB_NAME=railway
#PROD_DB_PASSWORD=9j0QkuUaC79dhs1ZEsv0
#PROD_DB_USERNAME=postgres